package utils

const (
	MsgInternalServerError    = "internal server error"
	MsgInvalidRequestBody     = "invalid request body"
	MsgUnauthorized           = "unauthorized"
	MsgForbidden              = "forbidden"
	MsgNotFound               = "not found"
	MsgInvalidPostID          = "invalid post id"
	MsgInvalidCommentID       = "invalid comment id"
	MsgInvalidUserID          = "invalid user id"
	MsgInvalidGroupID         = "invalid group id"
	MsgInvalidAuthorID        = "invalid author_id"
	MsgInvalidNotificationID  = "invalid notification id"
	MsgInvalidFollowRequestID = "invalid follow request id"
	MsgInvalidInvitationID    = "invalid invitation id"
	MsgInvalidJoinRequestID   = "invalid join request id"
	MsgInvalidEventID         = "invalid event id"
	MsgInvalidConversationID  = "invalid conversation id"
	MsgInvalidMessageID       = "invalid message id"
	MsgInvalidEmoji           = "invalid emoji"
	MsgInvalidUpload          = "invalid upload"
	MsgInvalidUploadType      = "invalid upload type"
	MsgInvalidUploadKind      = "invalid upload kind"
	MsgCommentsNotFound       = "comments not found"
	MsgProfileNotFound        = "profile not found"
	MsgPostNotFound           = "post not found"
	MsgUserNotFound           = "user not found"
	MsgGroupNotFound          = "group not found"
	MsgFollowRequestNotFound  = "follow request not found"
	MsgFollowRequestExists    = "follow request already exists"
	MsgCannotFollowSelf       = "cannot follow self"
	MsgNotFollowing           = "not following"
	MsgFollowNotPending       = "follow request is not pending"
	MsgInvalidStatus          = "invalid status"
	MsgInvalidGroupTitle      = "invalid group title"
	MsgCannotInviteSelf       = "cannot invite self"
	MsgAlreadyGroupMember     = "already a group member"
	MsgGroupInvitationExists  = "group invitation already exists"
	MsgGroupJoinRequestExists = "group join request already exists"
	MsgInvitationNotFound     = "group invitation not found"
	MsgJoinRequestNotFound    = "group join request not found"
	MsgCannotLeaveGroup       = "cannot leave the group"
	MsgInvalidEventTitle      = "invalid event title"
	MsgInvalidEventTime       = "invalid event time"
	MsgInvalidEventResponse   = "invalid event response"
	MsgEventNotFound          = "event not found"
	MsgConversationNotFound   = "conversation not found"
	MsgMessageNotFound        = "message not found"
	MsgInvalidLimit           = "invalid limit"
	MsgInvalidOffset          = "invalid offset"
	MsgInvalidCredentials     = "invalid credentials"
)

const (
	DefaultLimit = 10
	MaxLimit     = 100
)
