services:
  postgres:
    image: postgres:16
    container_name: social-network-postgres
    environment:
      POSTGRES_USER: social-network-role
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: social-network-db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social-network-role -d social-network-db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
